version: 0.0         # CodeDeploy 버전 (항상 0.0)
os: linux            # 대상 OS (보통 EC2는 Linux)

files: # 어떤 파일을 어디에 복사할지
  - source: /        # GitHub Actions에서 압축한 루트 전체
    destination: /home/ubuntu/sopkathon-server  # EC2에서의 대상 디렉토리
    overwrite: yes  # 이미 존재하는 파일 덮어쓰기

file_exist_behavior: OVERWRITE # 파일이 존재할 때의 동작 (OVERWRITE, RETAIN, REPLACE)

permissions: # 파일 권한 설정
  - object: /  # 권한을 설정할 디렉토리
    pattern: "**"  # 모든 파일과 디렉토리
    owner: ubuntu  # 소유자
    group: ubuntu  # 그룹

hooks: # 배포 단계에서 실행할 스크립트들
  ApplicationStart: # 압축 해제 후 실행할 단계
    - location: scripts/deploy.sh  # 실행할 스크립트 위치 (배포 디렉토리 기준)
      timeout: 60                   # 최대 실행 시간(초)
      runas: ubuntu                # 어떤 유저로 실행할지 (보통 EC2 로그인 계정)