name: CI/CD Pipeline

# main 브랜치에 push 또는 pull request가 발생할 때 실행
# feature/{feature-name} : 새로운 기능이나 버그 수정 작업 브랜치
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT_NAME: sopkathon-server
  BUCKET_NAME: sopkathon-s3-bucket
  CODE_DEPLOY_APP_NAME: sopkathon-app
  DEPLOYMENT_GROUP_NAME: sopkathon-deploy-group

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create application.yml
        run: echo "${{ secrets.APPLICATION_PROD_YML }}" > src/main/resources/application.yml

      # gradlew 파일 실행권한 설정
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 빌드 시작
      - name: Build with Gradle
        run: ./gradlew build -x test

      # 프로젝트 zip파일로 압축
      - name: Make Zip File
        if: github.event_name == 'push'
        run: zip -qq -r ./$GITHUB_SHA.zip .

      # aws 접근 id, key
      - name: Configure AWS credentials
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # s3에 압축한 zip파일 업로드
      - name: Upload to S3
        if: github.event_name == 'push'
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      # s3에 업로드한 파일 code Deploy에서 배포 요청
      # Deploy with AWS CodeDeploy
      - name: Deploy with AWS CodeDeploy
        if: github.event_name == 'push'
        run: |
          aws deploy create-deployment \
            --application-name $CODE_DEPLOY_APP_NAME \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name $DEPLOYMENT_GROUP_NAME \
            --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip